spring:
  application:
    name: springboot-rabbitmq-scheduler
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #发布确认
    publisher-confirms: true
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2000
        default-requeue-rejected: false
  #mysql连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  #mongodb
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      name: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    com.shuangyu: INFO
  file: ./logs/test.log




